### ISSUE TITLE
Hi there. Search() is not working as expected. It is hanging up as I make a request. I believe the reason is kijiji updated their search functionality

### ISSUE THREAD

**Issue by mohaimenhasan** [mwpenny/kijiji-scraper#19]
I am trying to use the NPM module to make a request. However, the request is hanging up.

**Comment by mwpenny** [comment]
Hi there, I'm sorry I only saw this now. I was able to successfully use the search functionality as expected using the latest version.

Could you please provide example code that reproduces the problem? Thanks!

**Comment by mwpenny** [comment]
Is this still a problem for you? I've been unable to reproduce it. I'd like to close this issue

**Comment by mwpenny** [comment]
Cannot reproduce. Closing
