### ISSUE TITLE
Any example of Location Id and Category Id?

### ISSUE THREAD

**Issue by thierryskoda** [mwpenny/kijiji-scraper#2]
I have tried a lot of location Id and Categorie Id and I always have an empty array.. :(

**Comment by mwpenny** [comment]
@thierryskoda Can you provide the values you tried?

**Comment by thierryskoda** [comment]
@mwpenny  I tried : 

```
{
    "locationId": "ontario",
    "categoryId": "cars"
}
```

But I'm not sure where to get those info. In the tutorial it says : 

> You can find them by using your browser's developer tools and performing a custom search on Kijiji.

But I'm not really sure to understand this part. 

Thank you !

**Comment by mwpenny** [comment]
@thierryskoda `locationId` and `categoryId` are integers, not strings. Kijiji uses them internally when you select your location and category on the website. You can find the `locationId`/`categoryId` values you want by performing a search and looking at the POST request parameters or the URL you are redirected to.

For example, after setting my location to Ottawa and selecting the "cars & vehicles" category, Kijiji redirects me to `http://www.kijiji.ca/b-cars-vehicles/ottawa/c27l1700185`. The last part of the URL (`c27l1700185`) is formatted as `c[categoryId]l[locationId]`. So in this case, `categoryId` is 27 and `locationId` is 1700185.

Perform your custom search on Kijiji and then check the URL for the corresponding Id values.

**Comment by thierryskoda** [comment]
@mwpenny  Oh thanks! I tried this and this still returning me empty array. Am I missing something else?

```
var kijiji = require("kijiji-scraper")

var prefs = {
    "locationId": 27,
    "categoryId": 1700185
}

var params = {
    "minPrice": 0,
    "maxPrice": 100000,
    "keywords": "toyota",
    "adType": "OFFER"
}

kijiji.query(prefs, params, function(err, ads) {
    //Use the ads array
    console.log(ads);
});
```

**Comment by mwpenny** [comment]
@thierryskoda It looks like you have your `locationId` and `categoryId` values switched.

**Comment by thierryskoda** [comment]
@mwpenny Wow sorry for this mistake.. Now it works! Thank you very much!!!

**Comment by mwpenny** [comment]
@thierryskoda Glad to help!
