### ISSUE TITLE
Invalid Kijiji HTML on search results page.

### ISSUE THREAD

**Issue by thisisloze** [mwpenny/kijiji-scraper#22]
So I was running my script for 24+ hours successfully. Then came home to this error.

`Error: Invalid Kijiji HTML on search results page
    at /home/loze/node_modules/kijiji-scraper/lib/search.js:129:19
    at process._tickCallback (internal/process/next_tick.js:68:7)
`

I'm not sure why it ran flawlessly for so long before returning this error. Any clue?

**Comment by thisisloze** [comment]
From what I can tell - it looks like its returning a body. But when `let results = parseResultsHTML(body);`

That returns null.

So possibly did kijiji change something so that the new html can't be parsed with cheerio?

**Comment by thisisloze** [comment]
Started getting results by changing 
`/* Extracts ad information from the HTML of a Kijiji ad results page */
function parseResultsHTML(html) {
    let adResults = null;  // Will remain null if the HTML can't be parsed
    let $ = cheerio.load(html);

    // Get info for each ad
    let allAdElements = $(".search-item");
    let filteredAdElements = allAdElements.not(".third-party");
    filteredAdElements.each(function(i, item) {
        try {
            let url = KIJIJI_BASE_URL + $(item).find("a.title").attr("href");
            let info = {
                "title": $(item).find(".title").text().trim(),
                "image": $(item).find(".image img").attr("src").replace(IMG_REGEX, "/$_57.JPG"),
                "date": dateFromRelativeDateString($(item).find(".date-posted").text().trim()),
                "description": $(this).find(".description").text().trim(),
            };
            console.log(info)
            adResults = adResults || [];
            adResults.push(new KijijiAd(url, info));
        } catch(e) {
            // Invalid ad
            console.warn(`WARNING: Failed to parse search result\n${e}`);
        }
    });
    return adResults;
}`

Not really familiar with cherrio or scraping in general - so not sure if this is where the bug lies.
But it looks like kijiji changed the names of the divs and classes for certain items possibly yesterday?

Is this what I should be doing to fix it - or am I totally off course here?

**Comment by DorianClair** [comment]
You saved my ass @thisisloze I was having the same issue your fix works perfectly 👍

**Comment by mwpenny** [comment]
Hey, thanks for letting me know! I'll look more into it and push fix when I get some time later this week/weekend

**Comment by thisisloze** [comment]
Glad to know that I was on the right track! How frequently has kijiji done this? Ive only used the script for a day and they changed it basically 24 hours after. Hopefully its not a everyday type thing.

**Comment by mwpenny** [comment]
I've found that it's relatively infrequent, maybe every 6 months or so, worst case.  Sometimes the stretches are much longer. Sounds like you got unlucky. I've tried to make this as resilient as I can but sometimes there's no avoiding it

EDIT: I just checked the commit history. The last *breaking* change like this on Kijiji's end was July 2017. However sometimes they change minor things so it may grab certain metadata incorrectly, but still parse the ad in a reasonable way. The latter is certainly much more common (I think I said 6 months because there was something like that recently). Additionally, the way ad data is retrieved is more resilient than the way search results are retrieved since it uses a JavaScript object in the page over scraping HTML elements

**Comment by mwpenny** [comment]
@thisisloze, I have confirmed the bug and you are correct that it is on Kijiji's end. Your fix is exactly what is needed to fix it - just scrape using the updated class names. I am pushing the fix now. Thanks again for opening this issue

**Comment by mwpenny** [comment]
Published to NPM

**Comment by thisisloze** [comment]
Cool! Thanks for the information! I for sure got unlucky haha! Sounds good!
