### ISSUE TITLE
Can't retrieve ads using webpack proxy

### ISSUE THREAD

**Issue by kevincote** [mwpenny/kijiji-scraper#25]
Hi,

I'm trying to make this work with in a basic Vue project build with Vue CLI 3 and using webpack. Since I can't directly fetch https://www.kijiji.ca using fetch() (it's returning a CORS error), i changed in the source code the KIJIJI_BASE_URL variable to "/kijiji" and set a proxy in my webpack config: 

```
"devServer": {
    proxy: {
      "/kijiji":  {
        target: "https://www.kijiji.ca",
        pathRewrite: { '^/kijiji': '' }
      }
    }
  }
```

Using this configuration, im getting a response.status = 200 in the fetch of function initFirstResultPagePath() but it seems there is a problem after that when trying to parse the body.
If I set a breakpoint on `let results = parseResultsHTML(body);`, what I have in body is:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="icon" href="/favicon.ico">
    <title>ad_scraper</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@mdi/font@latest/css/materialdesignicons.min.css">
  <link href="/js/app.js" rel="preload" as="script"><link href="/js/chunk-vendors.js" rel="preload" as="script"></head>
  <body>
    <noscript>
      <strong>We're sorry but ad_scraper doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
    </noscript>
    <div id="app"></div>
    <!-- built files will be auto injected -->
  <script type="text/javascript" src="/js/chunk-vendors.js"></script><script type="text/javascript" src="/js/app.js"></script></body>
</html>
```

Any idea it's not working using a proxy for kijiji website?

Thanks

**Comment by mwpenny** [comment]
Sorry for the late reply. It looks like this is likely an issue with your proxy configuration (the body seems like the main page of your web app).

I'd try getting it to proxy `/kijiji` requests using a web browser first, then switching over to modifying the module once that's confirmed to be working.

I found this page which might be helpful. https://vuejs-templates.github.io/webpack/proxy.html

Joyeuses fêtes !

**Comment by kevincote** [comment]
I fixed my problem. Instead of setting up a proxy, I've set up an Express backend in my app which allows CORS request. The kijiji.search() method is called by the back-end instead of the front-end, which solves the problem.

**Comment by mwpenny** [comment]
Perfect good to hear it's resolved
