### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by hassanshaikley** [mwpenny/kijiji-scraper#3]
Hey! How do you find location id's and category id's? Thanks!!

**Comment by mwpenny** [comment]
@hassanshaikley  You can find the `locationId`/`categoryId` values you want by performing a search and looking at the POST request parameters or the URL you are redirected to.

For example, after setting my location to Ottawa and selecting the "cars & vehicles" category, Kijiji redirects me to `http://www.kijiji.ca/b-cars-vehicles/ottawa/c27l1700185`. The last part of the URL (`c27l1700185`) is formatted as `c[categoryId]l[locationId]`. So in this case, `categoryId` is 27 and `locationId` is 1700185.

Perform your custom search on Kijiji and then check the URL for the corresponding Id values. Someone else has asked this question as well (issue #2). I can add something to the readme about this.
