### ISSUE TITLE
Issues with search for services?

### ISSUE THREAD

**Issue by matt1549** [mwpenny/kijiji-scraper#34]
I'm trying to search for services as oppose to buy and sell, but results empty.
Tried different category Ids and manually typing out the name. 
E.g. "categoryId: 84" and "categoryId: SERVICES.WEDDING" both come up empty.

Appreciate any help on this!

**Comment by mwpenny** [comment]
Hi there. Could you please post the code you are using, including all options passed to the `search()` function (such as `locationId`)?

Also, are there results when you perform the same search on the Kijiji website?

**Comment by matt1549** [comment]
If you sub in the category ID to 79 instead of 27 in the example code, you get the same error. 
Applies with any other service ID.
No issues seeing the actual results on the Kijiji webiste.

E.g.

const kijiji = require("kijiji-scraper");

let options = {
    minResults: 40
};

let params = {
    locationId: 1700185,  // Same as kijiji.locations.ONTARIO.OTTAWA_GATINEAU_AREA.OTTAWA
    categoryId: **79**,  // Same as kijiji.categories.CARS_AND_VEHICLES
    sortByName: "priceAsc"  // Show the cheapest listings first
};

// Scrape using returned promise
kijiji.search(params, options).then(function(ads) {
    // Use the ads array
    for (let i = 0; i < ads.length; ++i) {
        console.log(ads[i].title);
    }
}).catch(console.error);

// Scrape using optional callback parameter
function callback(err, ads) {
    if (!err) {
        // Use the ads array
        for (let i = 0; i < ads.length; ++i) {
            console.log(ads[i].title);
        }
    }
}
kijiji.search(params, options, callback);

**Comment by mwpenny** [comment]
Alright, I had a chance to look at this closer and it turns out that Kijiji uses slightly different markup on the results page for services compared to other categories. I'm not sure why or if they do this for other categories as well. It's possible they're in the process of transitioning to new markup site-wide. That's happened before and they changed it gradually for _some_ ads, rather than site-wide.

Good find! I have a hacked together fix working locally and will be able to clean it up and test a bit more thoroughly tomorrow.

**Comment by matt1549** [comment]
That's pretty interesting - definitely wouldn't have figured that out myself. Thank you for putting all this together. Appreciate it!

**Comment by mwpenny** [comment]
Hi, please check out the branch [services-search-fix](https://github.com/mwpenny/kijiji-scraper/tree/services-search-fix) and try your search again using that. I did some testing and your issue should be resolved. I will merge, then publish to npm after confirmation.

**Comment by matt1549** [comment]
Sorry for the late reply. Thank you for the fix. It works perfectly. Tried a few different categories and haven't run into any issues. Awesome work!

**Comment by mwpenny** [comment]
Great to hear! I've merged and the update is live on npm.
