### ISSUE TITLE
"npm install" fails

### ISSUE THREAD

**Issue by psommerfeld** [mwpenny/kijiji-scraper#44]
Is there an issue building this? I have not used npm before. I've tried npm rebuild followed by npm install.

$ npm install

> kijiji-scraper@6.0.0 prepare D:\data\Dropbox\work\kijiji\kijiji-scraper
> npm run build

> kijiji-scraper@6.0.0 build D:\data\Dropbox\work\kijiji\kijiji-scraper
> tsc

lib/backends/api-scraper.ts:16:24 - error TS2339: Property 'attribs' does not exist on type 'Element'.
  Property 'attribs' does not exist on type 'TextElement'.

16     const type = (item.attribs.type || "").toLowerCase();
                          ~~~~~~~

lib/backends/api-scraper.ts:17:34 - error TS2339: Property 'attribs' does not exist on type 'Element'.
  Property 'attribs' does not exist on type 'TextElement'.

17     const localizedLabel = (item.attribs["localized-label"] || "").toLowerCase();
                                    ~~~~~~~

lib/backends/api-scraper.ts:60:26 - error TS2339: Property 'attribs' does not exist on type 'Element'.
  Property 'attribs' does not exist on type 'TextElement'.

60         const url = item.attribs.href;
                            ~~~~~~~

lib/backends/api-scraper.ts:69:27 - error TS2339: Property 'attribs' does not exist on type 'Element'.
  Property 'attribs' does not exist on type 'TextElement'.

69         const name = item.attribs.name;
                             ~~~~~~~

Found 4 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kijiji-scraper@6.0.0 build: `tsc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kijiji-scraper@6.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Peter-laptop\AppData\Roaming\npm-cache\_logs\2020-12-11T02_19_18_268Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kijiji-scraper@6.0.0 prepare: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kijiji-scraper@6.0.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Peter-laptop\AppData\Roaming\npm-cache\_logs\2020-12-11T02_19_18_322Z-debug.log

**Comment by mwpenny** [comment]
The module depends on Typescript "^4.0.1" (i.e., take minor releases) and I have a feeling there was a breaking change. Looks like type checking got more strict.

I'll have time to look into this later today.

**Comment by technoligest** [comment]
I have a fix for this, but getting an error trying to push my branch.

git push --set-upstream origin yaser/cheerio
ERROR: Permission to mwpenny/kijiji-scraper.git denied to technoligest.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

If you can give me access somehow, I can push a pr out.

**Comment by mwpenny** [comment]
@technoligest You need to create a fork and then open a pull request

**Comment by technoligest** [comment]
https://github.com/mwpenny/kijiji-scraper/pull/45

wasn't able to link the issue, but here's the link to the pr

**Comment by mwpenny** [comment]
Yet again Cheerio breaks us 😛

**Comment by psommerfeld** [comment]
So will this be fixed? Sorry I don't know what the issues are.

**Comment by mwpenny** [comment]
It will be fixed. I'm waiting on @technoligest to respond to my feedback on his PR which resolves the issue.

I can push a fix if he doesn't respond in a day or two.

**Comment by technoligest** [comment]
I pushed the changes, sorry for the delay :)

**Comment by mwpenny** [comment]
Fix is in, thank you @technoligest 👍
