### ISSUE TITLE
kijiji.search() Randomly Returns an Amount of Ads Under Specified Amount via minResults

### ISSUE THREAD

**Issue by DudeManGuy0** [mwpenny/kijiji-scraper#50]
I'm running into an issue where sometimes `minResults` will be set to a value like 40, and the ads returned will sometimes be 40 or sometimes be 20. Say I set `minResults` to 120, the amount of ads returned can be anything between 20 and 120 and it is completely random from the testing I've done. I've included a video below for reproduction steps using version 6.1.0:

This behavior is new so it might have been introduced a few versions ago. Also, I apologize for the bad quality but I couldn't be bothered to find out why OBS is making my screen look blurry. The breakpoints are used to rule out my bad programming as a cause and verify the values as what they should be.

If you want me to write a code sample for you, I could do that.

**Comment by mwpenny** [comment]
Thanks for the clear reproduction steps. This looks like a pretty simple problem.

To detect whether or not the module has received all of the results, I check to see if the current page of results contains a link to the next page. If there is no next page link, we have received all of the results. This is done using a regex. But sometimes the result XML has:

```xml
<types:link href="http://link-to-next-page" rel="next"/>
```

and other times it has

```xml
<types:link rel="next" href="http://link-to-next-page"/>
```

The regex can't handle the different ordering of tags. I'll switch it to actually parse the XML.

**Comment by DudeManGuy0** [comment]
That's why you aren't supposed to parse XML/HTML with Regex. [See first answer](https://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags`)

Jokes aside, you may want to switch to an XML parsing library to avoid stuff like this from occurring in the future, but only if you think it will happen again. Otherwise it's a waste of time. Thanks for the bug fixes!

**Comment by mwpenny** [comment]
Haha that's right. In this case it seemed good enough, but it looks like I was wrong! Never trust consistency in foreign input.

I'm already using an HTML+XML parsing library ([cheerio](https://www.npmjs.com/package/cheerio)) for everything else in this module, so it makes sense to use it for this too. Now everything is more consistent.

Try with the latest (6.1.1).

**Comment by DudeManGuy0** [comment]
Works well!
