### ISSUE TITLE
Not Parsing Ads as of July 20, 2017

### ISSUE THREAD

**Issue by ve3qft** [mwpenny/kijiji-scraper#6]
It looks like ad-scraper.js stopped working today, presumably due to a change in the ad format.

ad-scraper.js is definitely getting the correct URL for the ad, but the information it is returning (price, image, etc.) is undefined.

**Comment by mwpenny** [comment]
Thank you for letting me know. I'll have time to confirm/look at this later today (though PRs are welcome in the mean time 😜)

**Comment by mwpenny** [comment]
Fixed. I did some testing and it seems that these ad layout changes have not been applied to all ads (maybe a slow rollout or something). Please try with the latest commit, it should work for both types of ads. I will push to NPM after testing more.

**Sidenote:** these new pages contain a pretty nice JS object in the HTML that should make this module fairly resilient to future layout changes.

**Comment by ve3qft** [comment]
Thanks for that! If I understood the JS well enough I would help out, but I
put a few console log statements in and that was about all I could do.

Heather

**Comment by ve3qft** [comment]
That worked perfectly! Thank-you very much!

I'll have a look at the code and see what you did.

Excellent!

Heather
