### ISSUE TITLE
Ad #... does not exist

### ISSUE THREAD

**Issue by patricksebastien** [mwpenny/kijiji-scraper#60]
I am trying to search for ads and sometimes I get:
```
Error: Kijiji returned error: Ad #1553278802 does not exist
    at parseResponseXML (node_modules/kijiji-scraper/dist/lib/backends/api-scraper.js:49:15)
    at node_modules/kijiji-scraper/dist/lib/backends/api-scraper.js:124:16
```

How to skip it?

**Comment by mwpenny** [comment]
Hi there. It looks like you're trying to scrape a specific ad using its URL, rather than searching. This error can happen if the ad URL you use is invalid or old. 

Can you provide some sample code that reproduces the issue?

**Comment by patricksebastien** [comment]
@mwpenny Code-18 - sorry for the noise, closing.
