### ISSUE TITLE
Kijiji Update ?

### ISSUE THREAD

**Issue by charleslav** [mwpenny/kijiji-scraper#75]
This morning, no data was getting scrape.
My kijiji-scraper version :     "kijiji-scraper": "^6.3.6",
Here a little test that i did:
const kijiji = require('kijiji-scraper');

const options = {
  categoryId: 36, 
  locationId: 1700124, 
};

kijiji.search(options, null).then((ads) => {
  console.log('Number of ads fetched:', ads.length);
  console.log(ads);
}).catch((err) => {
  console.error('Error fetching ads:', err);
});

Response :
Number of ads fetched: 0
[]

**Comment by Kornelsen** [comment]
+1

**Comment by mwpenny** [comment]
Kijiji changed their markup. Fixed in latest version. Give it a try.

**Comment by charleslav** [comment]
Work perfectly, thanks
