### ISSUE TITLE
recommended proxy rotation to avoid getting blacklisted?

### ISSUE THREAD

**Issue by vesper8** [mwpenny/kijiji-scraper#9]
I know this is a bit out of scope but just thought I'd ask to see if maybe you're already aware of something that works well for this purpose

basically i'm going to be doing a lot of queries from a single server with static ip and want to avoid getting blacklisted. Can you recommend a service and a package (node-friendly I imagine) that would wrap your kijiji-scraper well and easily?

thanks!!

**Comment by mwpenny** [comment]
How many queries is "a lot"? I used to scrape hourly when I was looking for apartments a couple years ago (this project's original purpose) and never got blacklisted/blocked or rate limited. @MrDOS was doing something similar more recently than me and actually submitted a PR which lowers network usage when searching (#4). You might want to also ask him if he encountered any problems with frequent scraping.

As for options, a quick search reveals [bumboo](https://github.com/fbaiodias/bumboo), which might be what you're looking for. It wraps the connection, intercepting network requests and sending them through a random proxy server provided by [Hide My Ass](https://www.hidemyass.com/index). bumboo hasn't been updated in ~8 months, but it is still probably worth a look at (according to the author, it is a "hack, done just for the fun").

I would try actually using the scraper in your project first and then determining if you need a proxy. I don't think you need to worry about it, but what you are describing is definitely possible if you want to.

**Comment by vesper8** [comment]
thanks for the tips!

tbh I don't have any doubts that I would get into trouble, but I felt like learning something and making it more sturdy / future-proof in case I decide to start letting other people use the interface i'm building

I'll look into bumboo. thanks!

**Comment by mwpenny** [comment]
No problem. Good luck on your project! I'll close this issue.

**Comment by MrDOS** [comment]
Just my $0.02 – I scraped every 10 minutes for about a month with `scrapeInnerAd` as `false` and encountered no issues. If your project already requires that you cache ads (or at least their IDs) then this approach works very well.
